# application.yml - # application.properties - Sending Simple Email with JavaMailSender Example

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com

    username: maissa1922@gmail.com
    password: maissa53794144

  

    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
